name = "edgetunnel" # todo
#name = "cf-worker-connect-test" # todo
#main = "test/worker/cf-cdn-cgi-trace2.js"

#main = "test/worker/worker-connect-test.js"
main = "src/worker-vless.js"

compatibility_date = "2024-04-15"

[vars]
UUID = "f3ce1e7e-cb1c-4fa5-a6f3-09733b173b81"
